// Generated by CoffeeScript 1.4.0
var match;

match = function() {
  console.log({
    match: arguments
  });
  return false;
};

module.exports = function(Preparator, decoratedFn) {
  return function() {
    if (Preparator["if"] == null) {
      return;
    }
    if (Preparator["if"].match == null) {
      return;
    }
    if (!match(Preparator["if"].match, arguments)) {
      return;
    }
    return decoratedFn.apply(self, arguments);
  };
};
