// Generated by CoffeeScript 1.4.0
var matchAll;

matchAll = function(matcher, obj) {
  var doesCount, key, shouldCount;
  shouldCount = 0;
  doesCount = 0;
  for (key in matcher) {
    if ((obj[key] != null) && obj[key] === matcher[key]) {
      doesCount++;
    }
    shouldCount++;
  }
  return shouldCount === doesCount;
};

module.exports = function(Preparator, decoratedFn) {
  return function() {
    if (Preparator["if"] == null) {
      return;
    }
    if (Preparator["if"].matchAll == null) {
      return;
    }
    if (!matchAll(Preparator["if"].matchAll, arguments[0])) {
      return;
    }
    return decoratedFn.apply(this, arguments);
  };
};
