// Generated by CoffeeScript 1.6.3
var defer,
  __slice = [].slice;

defer = require('when').defer;

module.exports = function(fn) {
  return function() {
    var args, doing, error;
    args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    doing = defer();
    try {
      fn.apply(this, [doing].concat(args));
    } catch (_error) {
      error = _error;
      doing.reject(error);
    }
    return doing.promise;
  };
};
