// Generated by CoffeeScript 1.6.3
var __slice = [].slice;

module.exports = function() {
  var args, decoratedFn, remains, _i;
  args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
  remains = 2 <= args.length ? __slice.call(args, 0, _i = args.length - 1) : (_i = 0, []), decoratedFn = args[_i++];
  return function() {
    return decoratedFn.apply(this, arguments);
  };
};
