// Generated by CoffeeScript 1.4.0
var Defer, argsOf, sequence;

argsOf = require('../util').argsOf;

Defer = require('when').defer;

sequence = require('when/sequence');

module.exports = function(Preparator, decoratedFn) {
  var seq, _id;
  seq = 0;
  _id = seq;
  if (typeof Preparator !== 'object' || Preparator instanceof Array) {
    throw new Error('also.inject.async(Preparator, decoratedFn) requires Preparator as object');
  }
  if (Preparator.parallel == null) {
    Preparator.parallel = true;
  }
  return (function(context, beforeAllDone) {
    var afterAll, beforeAll, calls, queue, queueLength, running;
    context.signature = argsOf(decoratedFn);
    queue = [];
    calls = [];
    running = false;
    queueLength = function() {
      var call, item, length, _i, _j, _len, _len1;
      length = 0;
      if (Preparator.parallel) {
        for (_i = 0, _len = queue.length; _i < _len; _i++) {
          item = queue[_i];
          if (!item.done) {
            length++;
          }
        }
      } else {
        for (_j = 0, _len1 = calls.length; _j < _len1; _j++) {
          call = calls[_j];
          length++;
        }
      }
      return length;
    };
    beforeAll = function() {
      var defer, done;
      defer = Defer();
      if (beforeAllDone) {
        return defer.resolve();
      }
      if (typeof Preparator.beforeAll !== 'function') {
        return defer.resolve();
      }
      beforeAllDone = true;
      done = function(result) {
        if (result instanceof Error) {
          return defer.reject(result);
        }
        return defer.resolve(result);
      };
      Preparator.beforeAll(done, context);
      return defer.promise;
    };
    afterAll = function() {
      var defer, done;
      defer = Defer();
      if (typeof Preparator.afterAll !== 'function') {
        return defer.resolve();
      }
      done = function(result) {
        _id = -1;
        if (result instanceof Error) {
          return defer.reject(result);
        }
        return defer.resolve(result);
      };
      _id = -1;
      Preparator.afterAll(done, context);
      return defer.promise;
    };
    Object.defineProperty(context, 'args', {
      enumerable: true,
      get: function() {
        try {
          return queue[_id].args;
        } catch (_error) {}
      }
    });
    Object.defineProperty(context, 'defer', {
      enumerable: true,
      get: function() {
        queue[_id].altDefer = true;
        try {
          return queue[_id].defer;
        } catch (_error) {}
      }
    });
    Object.defineProperty(context, 'first', {
      enumerable: true,
      get: function() {
        try {
          return queue[_id].first;
        } catch (_error) {}
      }
    });
    Object.defineProperty(context, 'last', {
      enumerable: true,
      get: function() {
        try {
          return queue[_id].last;
        } catch (_error) {}
      }
    });
    Object.defineProperty(context, 'queue', {
      enumerable: true,
      get: function() {
        return {
          length: queueLength()
        };
      }
    });
    return function() {
      var finished, fn, run;
      finished = Defer();
      fn = function(finished, args) {
        var afterEach, arg, beforeEach, callDecoratedFn, id, inject, _i, _len;
        id = seq++;
        inject = [];
        for (_i = 0, _len = args.length; _i < _len; _i++) {
          arg = args[_i];
          inject.push(arg);
        }
        queue[id] = {
          done: false,
          defer: Defer(),
          altDefer: false,
          first: [],
          last: [],
          args: inject
        };
        beforeEach = function() {
          var defer, done;
          defer = Defer();
          if (typeof Preparator.beforeEach !== 'function') {
            return defer.resolve();
          }
          done = function(result) {
            _id = id;
            finished.notify({
              beforeEach: result
            });
            if (result instanceof Error) {
              return defer.reject(result);
            }
            return defer.resolve(result);
          };
          _id = id;
          Preparator.beforeEach(done, context);
          return defer.promise;
        };
        callDecoratedFn = function() {
          _id = id;
          if (queue[id].altDefer) {
            decoratedFn.apply(null, queue[id].first.concat(inject).concat(queue[id].last));
          } else {
            decoratedFn.apply(null, [
              function(result) {
                finished.notify({
                  result: result
                });
                if (result instanceof Error) {
                  return queue[id].defer.reject(result);
                }
                return queue[id].defer.resolve(result);
              }
            ].concat(queue[id].first.concat(inject).concat(queue[id].last)));
          }
          return queue[id].defer.promise;
        };
        afterEach = function() {
          var defer, done;
          _id = id;
          defer = Defer();
          if (typeof Preparator.afterEach !== 'function') {
            queue[id].done = true;
            if (queueLength() === 0) {
              return afterAll();
            }
            return defer.resolve();
          }
          done = function(result) {
            _id = id;
            queue[id].done = true;
            finished.notify({
              afterEach: result
            });
            if (result instanceof Error) {
              defer.reject(result);
            } else {
              defer.resolve(result);
            }
            if (queueLength() === 0) {
              return afterAll();
            }
          };
          Preparator.afterEach(done, context);
          return defer.promise;
        };
        sequence([beforeAll, beforeEach, callDecoratedFn, afterEach]).then(function(results) {
          return finished.resolve(results[2]);
        }, function(error) {
          if (Preparator.error instanceof Function) {
            Preparator.error(error);
          }
          return done.reject(error);
        }, finished.notify);
        return finished.promise;
      };
      if (!Preparator.parallel) {
        calls.push({
          "function": fn,
          finished: finished,
          "arguments": arguments
        });
        run = function() {
          var call;
          running = true;
          call = calls.shift();
          if (call == null) {
            running = false;
            return;
          }
          return call["function"](call.finished, call["arguments"]).then(function() {
            return run();
          }, function() {
            return run();
          });
        };
        if (!running) {
          run();
        }
        return finished.promise;
      }
      if (Preparator.parallel) {
        return fn(finished, arguments);
      }
    };
  })(function() {}, false);
};
