// Generated by CoffeeScript 1.4.0
var argsOf;

argsOf = require('../util').argsOf;

module.exports = function(Preparator, decoratedFn) {
  return (function(context, configured) {
    context.preparator = Preparator;
    context.signature = argsOf(decoratedFn);
    context.first = [];
    context.last = [];
    if (context.preparator.beforeAll != null) {
      context.preparator.beforeAll(context);
    }
    return function() {
      var arg, _i, _j, _len, _len1;
      context.inject = typeof context.preparator === 'function' ? context.preparator(context.signature) : context.preparator instanceof Array ? context.preparator : context.preparator instanceof Object ? (configured = true, []) : [context.preparator];
      if (!configured) {
        for (_i = 0, _len = arguments.length; _i < _len; _i++) {
          arg = arguments[_i];
          context.inject.push(arg);
        }
        return decoratedFn.apply(null, context.first.concat(context.inject));
      }
      if (context.preparator.beforeEach != null) {
        context.preparator.beforeEach(context);
      }
      for (_j = 0, _len1 = arguments.length; _j < _len1; _j++) {
        arg = arguments[_j];
        context.inject.push(arg);
      }
      decoratedFn.apply(null, context.first.concat(context.inject).concat(context.last));
      if (context.preparator.afterEach != null) {
        return context.preparator.afterEach(context);
      }
    };
  })(function() {}, false);
};
