// Generated by CoffeeScript 1.4.0
var argsOf;

argsOf = require('../util').argsOf;

module.exports = function(Preparator, decoratedFn) {
  return (function(context, configured) {
    try {
      context.preparator.beforeAll();
    } catch (_error) {}
    return function() {
      var arg, injected, _i, _len;
      injected = typeof Preparator === 'function' ? Preparator(argsOf(decoratedFn)) : Preparator instanceof Array ? Preparator : Preparator instanceof Object ? (configured = true, []) : [Preparator];
      if (!configured) {
        for (_i = 0, _len = arguments.length; _i < _len; _i++) {
          arg = arguments[_i];
          injected.push(arg);
        }
        return decoratedFn.apply(null, injected);
      }
      try {
        context.preparator.beforeEach();
      } catch (_error) {}
      return decoratedFn.apply(null, null);
    };
  })({
    preparator: Preparator
  }, false);
};
