// Generated by CoffeeScript 1.4.0
var argsOf;

argsOf = require('../util').argsOf;

module.exports = function(Preparator, decoratedFn) {
  return (function(context, configured) {
    context.preparator = Preparator;
    context.signature = argsOf(decoratedFn);
    if (context.preparator.beforeAll != null) {
      context.preparator.beforeAll(context);
    }
    return function() {
      var arg, _i, _len;
      context.injects = typeof context.preparator === 'function' ? context.preparator(context.signature) : context.preparator instanceof Array ? context.preparator : context.preparator instanceof Object ? (configured = true, []) : [context.preparator];
      if (!configured) {
        for (_i = 0, _len = arguments.length; _i < _len; _i++) {
          arg = arguments[_i];
          context.injects.push(arg);
        }
        return decoratedFn.apply(null, context.injects);
      }
      if (context.preparator.beforeEach != null) {
        context.preparator.beforeEach(context);
      }
      decoratedFn.apply(null, null);
      if (context.preparator.afterEach != null) {
        return context.preparator.afterEach(context);
      }
    };
  })(function() {}, false);
};
