// Generated by CoffeeScript 1.6.3
var argsOf, defer;

defer = require('when').defer;

argsOf = require('../util').argsOf;

module.exports = function(opts, decoratedFn) {
  opts || (opts = {});
  decoratedFn || (decoratedFn = opts);
  if (typeof decoratedFn !== 'function') {
    throw new Error('expected function as last arg');
  }
  return function() {
    var arg, argPosition, deferral, newArgs, resolver, _i, _len;
    deferral = defer();
    if (opts.resolver != null) {
      argPosition = argsOf(decoratedFn).indexOf(opts.resolver);
      if (argPosition >= 0) {
        resolver = deferral.resolve;
        resolver.resolve = resolver;
        resolver.reject = deferral.reject;
        resolver.notify = deferral.notify;
        newArgs = [];
        for (_i = 0, _len = arguments.length; _i < _len; _i++) {
          arg = arguments[_i];
          newArgs.push(arg);
        }
        newArgs[argPosition] = resolver;
        decoratedFn.apply(this, newArgs);
      } else {
        decoratedFn.apply(this, arguments);
        deferral.resolve();
      }
      return deferral.promise;
    }
    decoratedFn.apply(this, arguments);
    deferral.resolve();
    return deferral.promise;
  };
};
