// Generated by CoffeeScript 1.6.3
var Also, exported, _i, _len, _ref,
  __slice = [].slice;

Also = function() {
  var args, definitions, exporter, futureArgs, moduleFactoryFn, objectName, _i, _results;
  args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
  exporter = args[0], futureArgs = 3 <= args.length ? __slice.call(args, 1, _i = args.length - 1) : (_i = 1, []), moduleFactoryFn = args[_i++];
  _results = [];
  for (objectName in (definitions = moduleFactoryFn({
    context: {}
  }))) {
    _results.push(exporter[objectName] = definitions[objectName]);
  }
  return _results;
};

_ref = ['validate', 'inject', 'deferral', 'schedule', 'match', 'util'];
for (_i = 0, _len = _ref.length; _i < _len; _i++) {
  exported = _ref[_i];
  Object.defineProperty(Also, exported, {
    enumerable: true,
    value: require("./" + exported)
  });
}

module.exports = Also;
