// Generated by CoffeeScript 1.6.3
var Also, exported, _i, _len, _ref,
  __slice = [].slice;

Also = function() {
  var args, futureArgs, moduleFactoryFn, _i;
  args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
  futureArgs = 2 <= args.length ? __slice.call(args, 0, _i = args.length - 1) : (_i = 0, []), moduleFactoryFn = args[_i++];
  return moduleFactoryFn({
    context: {}
  });
};

_ref = ['validate', 'inject', 'deferral', 'schedule', 'match', 'util'];
for (_i = 0, _len = _ref.length; _i < _len; _i++) {
  exported = _ref[_i];
  Object.defineProperty(Also, exported, {
    enumerable: true,
    value: require("./" + exported)
  });
}

module.exports = Also;
