// Generated by CoffeeScript 1.9.2
var defer,
  slice = [].slice;

defer = require('when').defer;

module.exports = function(fn) {
  return function() {
    var action, args;
    args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
    action = defer();
    fn.apply(this, [action].concat(args));
    return action.promise;
  };
};
