// Generated by CoffeeScript 1.9.2
var slice = [].slice;

module.exports = function(superFn, fn) {
  return function() {
    var args, instance, superclass;
    args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
    superclass = typeof superFn !== 'function' ? superFn : superFn.apply(this, args);
    instance = fn.apply(this, [superclass].concat(args));
    return instance;
  };
};
