// Generated by CoffeeScript 1.4.0
var argsOf;

argsOf = require('./util').argsOf;

exports.sync = function(signatureFn, fn) {
  return function() {
    return fn.apply(null, signatureFn(argsOf(fn)));
  };
};

exports.async = function(signatureFn, fn) {
  return function() {
    return signatureFn(argsOf(fn).slice(1), function(error, result) {
      return fn.apply(null, [error].concat(result));
    });
  };
};
