// Generated by CoffeeScript 1.4.0
var argsOf;

argsOf = require('./util').argsOf;

module.exports = {
  flat: function(singatureFn, fn) {
    return function() {
      return fn.apply(null, singatureFn(argsOf(fn)));
    };
  }
};
