// Generated by CoffeeScript 1.6.3
var dirname, lstatSync, root;

lstatSync = require('fs').lstatSync;

dirname = require('path').dirname;

module.exports = root = function(parent) {
  var length, path, paths;
  if (parent == null) {
    parent = module.parent;
  }
  if (parent.parent != null) {
    return root(parent.parent);
  }
  paths = parent.paths;
  length = paths.length;
  while (path = paths[--length]) {
    if (path.match(/node_modules$/)) {
      try {
        if (lstatSync(path).isDirectory()) {
          return {
            home: dirname(path)
          };
        }
      } catch (_error) {}
    }
  }
};
