// Generated by CoffeeScript 1.9.2
var dirname, lstatSync, root;

lstatSync = require('fs').lstatSync;

dirname = require('path').dirname;

module.exports = root = function(parent) {
  var home, i, len, path, ref;
  if (parent == null) {
    parent = module.parent;
  }
  if (parent.parent != null) {
    return root(parent.parent);
  }
  ref = parent.paths;
  for (i = 0, len = ref.length; i < len; i++) {
    path = ref[i];
    try {
      if (lstatSync(path).isDirectory()) {
        home = dirname(path);
        return {
          home: home
        };
      }
    } catch (_error) {}
  }
};
