// Generated by CoffeeScript 1.4.0

module.exports = {
  argsOf: function(fn) {
    try {
      return fn.toString().match(/function\s*\((.*)\)/)[1].replace(/\s/g, '').split(',').filter(function(arg) {
        if (arg !== '') {
          return true;
        }
      });
    } catch (error) {
      return [];
    }
  }
};
