// Generated by CoffeeScript 1.9.2
var uuid;

uuid = require('node-uuid');

module.exports = {
  argsOf: function(fn) {
    var error;
    try {
      return fn.toString().match(/function\s*\((.*)\)/)[1].replace(/\s/g, '').split(',').filter(function(arg) {
        if (arg !== '') {
          return true;
        }
      });
    } catch (_error) {
      error = _error;
      return [];
    }
  },
  uuid: uuid.v1
};
