// Generated by CoffeeScript 1.4.0
var wait;

wait = function(Preparator, decoratedFn) {
  if (typeof Preparator === 'function' && !(decoratedFn != null)) {
    decoratedFn = Preparator;
  }
  if (Preparator.until == null) {
    return function() {
      return decoratedFn.apply(this, arguments);
    };
  }
  return function() {
    if (Preparator.until() === true) {
      return decoratedFn.apply(this, arguments);
    }
  };
};

module.exports = wait;
