// Generated by CoffeeScript 1.4.0
var wait;

wait = function(Preparator, decoratedFn) {
  if (typeof Preparator === 'function' && !(decoratedFn != null)) {
    decoratedFn = Preparator;
  }
  if (Preparator.until == null) {
    return function() {
      return decoratedFn.apply(this, arguments);
    };
  }
  return function() {
    var interval;
    if (Preparator.until() === true) {
      return decoratedFn.apply(this, arguments);
    }
    return interval = setInterval((function() {
      try {
        if (Preparator.until() === true) {
          clearInterval(interval);
          return decoratedFn.apply(this, arguments);
        }
      } catch (error) {
        return clearInterval(interval);
      }
    }), Preparator.retry || 10);
  };
};

module.exports = wait;
